/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ink: '#111111',
        mute: '#6b7280',
        charcoal: '#374151',
        surface: '#fcf8ff',
        canvas: '#ffffff',
        'soft-cloud': '#f9fafb',
        'surface-container': '#f0ecf9',
        'surface-container-low': '#f5f2ff',
        hairline: '#e5e7eb',
        error: '#ef4444',
        primary: '#4f46e5',
        'primary-fixed': '#e2dfff',
        'primary-container': '#4338ca',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#3323cc',
        secondary: '#006c49',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        'surface-variant': '#e4e1ee',
        'on-surface-variant': '#464555',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        gutter: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        caption: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'button-md': ['15px', { lineHeight: '1', fontWeight: '600' }],
        'heading-md': ['18px', { lineHeight: '1.5', fontWeight: '600' }],
        'heading-lg': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'heading-xl': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      boxShadow: {
        soft: '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
      },
    },
  },
  plugins: [],
};
