name: auth-service

services:
  auth-service:
    image: ${IMAGE}:${IMAGE_TAG}
    restart: unless-stopped
    env_file: .env
    ports:
      - '127.0.0.1:3000:3000'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - auth-data:/app/backend/data

volumes:
  auth-data:
